name: restaurantapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  image_picker: ^1.0.7
  line_icons: ^2.0.3
  lottie: ^2.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/login/
    - assets/logo/
    - assets/internet/
